# Generated by Django 2.2.26 on 2022-02-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220215_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='subscription',
            field=models.IntegerField(null=True, verbose_name='Subscription'),
        ),
    ]
